// Nova Market — feed adapter (China-sourced product marketplace)
// Honest architecture (protocol §0s): "we do nothing" = AFFILIATE. The adapter is
// provider-agnostic so CJ / 1688 / dropshipping can flip on later WITHOUT a rebuild.
//
// Model policy (§0h): DeepSeek / Alibaba / Gemini only. No Anthropic.
// Product is English (§0d).

// ---------- provider registry ----------
// Each provider implements: search({keyword, category, page, size}) -> Product[]
// and link(product) -> tracked URL. Keys live in Cloudflare Worker Secrets, never
// in the repo (§0m E). Signing happens SERVER-side, never in the browser.

export const PROVIDERS = {
  aliexpress: {
    name: "AliExpress Affiliate",
    // aliexpress.affiliate.product.query — HMAC-signed. ~200M+ SKUs.
    // Requires: App Key, App Secret, Tracking ID (portals.aliexpress.com).
    commission: "3-9% by category",
    cookie: "3 days",
  },
  cj: {
    name: "CJ Dropshipping",
    // cjdropship.com/cj-api v3.1 — real-time stock, ~1.3M SKU, 60-day cookie.
    commission: "hybrid affiliate + fulfillment",
    cookie: "60 days",
  },
  "1688": {
    name: "1688 / Taobao",
    // open.1688.com — wholesale, best cost. Enterprise account + OAuth + GMV thresholds.
    commission: "dropshipping wholesale",
    cookie: "n/a (later phase)",
  },
};

// ---------- normalized product shape (all providers map here) ----------
// {
//   id, provider, title, description, price { value, currency }, originalPrice,
//   image, images[], categoryId, categoryName, commissionRate, affiliateUrl,
//   sellerRating, salesVolume, stockStatus, shipping
// }

// ---------- markup / pricing engine (dropshipping mode, later) ----------
// In AFFILIATE mode price shown = source price (we earn the provider commission).
// In DROPSHIPPING mode (later, Owner opts in) price = sourceCost * markup.
export function applyMarkup(sourceCost, { mode = "affiliate", markup = 3, currency = "EUR" } = {}) {
  if (mode !== "dropshipping") {
    return { mode, price: sourceCost, markupApplied: 1 };
  }
  const price = Number((sourceCost * markup).toFixed(2));
  return { mode, price, markupApplied: markup, currency };
}

// ---------- affiliate link builder (per provider) ----------
// AliExpress affiliate links are generated by the affiliate API (affiliate_link field)
// or by the deep-link converter; the tracking ID attributes the sale. This builder
// documents the shape; real links come from the provider response.
export function buildAffiliateLink(provider, product) {
  switch (provider) {
    case "aliexpress":
      // affiliate_link is returned directly by aliexpress.affiliate.product.query
      return product.affiliateLink || product.affiliateUrl || null;
    case "cj":
      return product.affiliateUrl || null;
    default:
      return null;
  }
}

// ---------- AliExpress affiliate API client (wired, exercised once keys land) ----------
// Signature = MD5( appSecret + sorted("keyvalue") + appSecret ), uppercase hex.
// This is the standard Alibaba "TOP" signature AliExpress uses. Server-side only.
// Honest: this path is NOT yet exercised end-to-end — it waits for the Owner's
// approval + App Key / App Secret / Tracking ID.

import { createHash } from "node:crypto";

export function aliExpressSign(params, secret) {
  const keys = Object.keys(params).sort();
  let raw = secret;
  for (const k of keys) {
    const v = params[k];
    if (v === undefined || v === null || v === "") continue;
    raw += k + v;
  }
  raw += secret;
  return createHash("md5").update(raw, "utf8").digest("hex").toUpperCase();
}

// Normalize an AliExpress product item into our catalog shape.
function normalizeAliExpress(item, trackingId) {
  const salePrice = Number(item.sale_price || item.target_sale_price || 0);
  const origPrice = Number(item.original_price || item.target_original_price || 0);
  return {
    slug: slugify(item.product_title) + "-" + item.product_id,
    title: item.product_title || "Untitled product",
    description: item.product_title || "",
    provider: "aliexpress",
    provider_id: String(item.product_id),
    image: item.product_main_image_url || item.product_small_image_urls?.string?.[0] || "",
    images: JSON.stringify(item.product_small_image_urls?.string || []),
    price: salePrice || origPrice || 0,
    price_currency: "EUR",
    original_price: origPrice > salePrice ? origPrice : null,
    commission_rate: item.commission_rate || null,
    affiliate_url: item.promotion_link || item.affiliate_link || null,
    seller_rating: Number(item.evaluate_rate || 0),
    sales_volume: Number(item.lastest_volume || item.sale_volume || 0),
  };
}

function slugify(s) {
  return String(s || "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 80);
}

// Search AliExpress by keyword, return normalized products.
// `env` must carry: ALIEXPRESS_APP_KEY, ALIEXPRESS_APP_SECRET, ALIEXPRESS_TRACKING_ID.
export async function searchAliExpress(env, { keyword, page = 1, pageSize = 20 } = {}) {
  const appKey = env?.ALIEXPRESS_APP_KEY;
  const secret = env?.ALIEXPRESS_APP_SECRET;
  const trackingId = env?.ALIEXPRESS_TRACKING_ID;
  if (!appKey || !secret || !trackingId) {
    return { ok: false, reason: "aliexpress-not-configured", products: [] };
  }
  const biz = {
    method: "aliexpress.affiliate.product.query",
    app_key: appKey,
    timestamp: new Date().toISOString().replace(/\.\d+Z$/, "Z").replace(/[-:]/g, "").replace("T", "").replace("Z", ""),
    sign_method: "md5",
    v: "2.0",
    format: "json",
    fields: "product_id,product_title,sale_price,original_price,product_main_image_url,product_small_image_urls,evaluate_rate,lastest_volume,commission_rate,promotion_link,affiliate_link",
    keywords: keyword,
    target_currency: "EUR",
    tracking_id: trackingId,
    page_no: String(page),
    page_size: String(pageSize),
  };
  biz.sign = aliExpressSign(biz, secret);
  try {
    const res = await fetch("https://api-sg.aliexpress.com/sync", {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded;charset=utf-8" },
      body: new URLSearchParams(biz).toString(),
      signal: AbortSignal.timeout(15000),
    });
    const data = await res.json();
    const items = data?.aliexpress_affiliate_product_query_response?.resp_result?.result?.products?.product || [];
    return { ok: true, products: items.map((i) => normalizeAliExpress(i, trackingId)) };
  } catch (e) {
    return { ok: false, reason: "aliexpress-fetch-failed", products: [], error: String(e) };
  }
}
